### ISSUE TITLE
SOCKS5 header not respected

### ISSUE THREAD

**Issue by davidmann4** [ickerwx/tcpproxy#29]
Hi, seems like the SOCKS5 welcome packet is not answered by the server

![image](https://user-images.githubusercontent.com/1736570/112736850-270c2980-8f56-11eb-96d7-f16c396eb8c0.png)

(i think i tried socks4 in this picture above, Socks5 has a shorter starting packet like 05 01 00  )

any idea how to get it working?

**Comment by ptitdoc** [comment]
Hello,

Thanks for testing.

Can you give more information ? Which command line did you use ?

You need to activate SOCKS explicitely
`--protocol {TCP,SOCKS}`

You can also enable more logging:
`-l DEBUG`

I still need to improve debugging with socks as it just print out some debugging information instead of properly using logging facilities. Please also note that only SOCKS5 is supported. I will change the `SOCKS` parameter to `SOCKS5` to highlight that.

**Comment by davidmann4** [comment]
did not provided `--protocol SOCKS` - will test it
