### ISSUE TITLE
Retrieve the destination server from a module

### ISSUE THREAD

**Issue by TheTechRobo** [ickerwx/tcpproxy#39]
Hi, I'm writing a module for this. One of the things I need to do is modify a specific message sent by the client to change some text to the hostname or IP address of the destination server.

I'd rather not have to specify it twice - once for the `-ti` parameter, and one for the module's parameter.

Thanks in advance!

**Comment by ickerwx** [comment]
This is a little obscure and not  documented, but you can already do it right now.

First, define `self.source == None` and  `self.destination == None` in den module's `__init__()` method. The proxy thread will then update these fields (see lines 286/287 in `tcpproxy.py`). You need to take care if the module is on the incoming or outgoing chain. `source` will always be the sending address, `destination` always the receiving address.

So in your case, when you're modifying data going to the server, you can then use `self.destination` to get the IP address of the server.

Disclaimer: it's been ages since I used this and I just looked at parts of the code, I didn't test it. Try it out and let me know how it works.

**Comment by TheTechRobo** [comment]
Thanks, that works!
